# Create a docker compose that run Meilisearch and Scrapix both latest version.
version: '3'

services:
  scrapix:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://redis:6379
    command: yarn serve

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - 7700:7700
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=masterKey
      - MEILI_ENV=development

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
